//! Closed instrument catalog; all 33 reference counters plus Rust lifecycle facts.
#[derive(Clone, Copy)]
pub(super) enum MetricScope {
    Cache,
    Memory,
    Distributed,
    Backplane,
}
#[derive(Clone, Copy)]
pub(super) enum MetricCounter {
    Set,
    TryGet,
    GetOrDefault,
    GetOrSet,
    Remove,
    Expire,
    RemoveByTag,
    Clear,
    Hit,
    Miss,
    FactorySyntheticTimeout,
    FactoryError,
    FactorySuccess,
    FailSafeActivate,
    EagerRefresh,
    MemorySet,
    MemoryGet,
    MemoryExpire,
    MemoryRemove,
    MemoryEvict,
    MemoryHit,
    MemoryMiss,
    DistributedSet,
    DistributedGet,
    DistributedRemove,
    DistributedHit,
    DistributedMiss,
    DistributedCircuitBreakerChange,
    SerializationError,
    DeserializationError,
    BackplanePublish,
    BackplaneReceive,
    BackplaneCircuitBreakerChange,
    OperationStarted,
    OperationCompleted,
    MemoryAdmissionRejected,
    BackgroundCommitError,
    MarkerRead,
    MarkerReceived,
    MarkerSnapshotWrite,
    MarkerEagerRefresh,
}
impl MetricCounter {
    pub(super) const COUNT: usize = 41;
    pub(super) const ALL: [Self; Self::COUNT] = [
        Self::Set,
        Self::TryGet,
        Self::GetOrDefault,
        Self::GetOrSet,
        Self::Remove,
        Self::Expire,
        Self::RemoveByTag,
        Self::Clear,
        Self::Hit,
        Self::Miss,
        Self::FactorySyntheticTimeout,
        Self::FactoryError,
        Self::FactorySuccess,
        Self::FailSafeActivate,
        Self::EagerRefresh,
        Self::MemorySet,
        Self::MemoryGet,
        Self::MemoryExpire,
        Self::MemoryRemove,
        Self::MemoryEvict,
        Self::MemoryHit,
        Self::MemoryMiss,
        Self::DistributedSet,
        Self::DistributedGet,
        Self::DistributedRemove,
        Self::DistributedHit,
        Self::DistributedMiss,
        Self::DistributedCircuitBreakerChange,
        Self::SerializationError,
        Self::DeserializationError,
        Self::BackplanePublish,
        Self::BackplaneReceive,
        Self::BackplaneCircuitBreakerChange,
        Self::OperationStarted,
        Self::OperationCompleted,
        Self::MemoryAdmissionRejected,
        Self::BackgroundCommitError,
        Self::MarkerRead,
        Self::MarkerReceived,
        Self::MarkerSnapshotWrite,
        Self::MarkerEagerRefresh,
    ];
    pub(super) const fn name(self) -> &'static str {
        match self {
            Self::Set => "amalgam.cache.set",
            Self::TryGet => "amalgam.cache.try_get",
            Self::GetOrDefault => "amalgam.cache.get_or_default",
            Self::GetOrSet => "amalgam.cache.get_or_set",
            Self::Remove => "amalgam.cache.remove",
            Self::Expire => "amalgam.cache.expire",
            Self::RemoveByTag => "amalgam.cache.remove_by_tag",
            Self::Clear => "amalgam.cache.clear",
            Self::Hit => "amalgam.cache.hit",
            Self::Miss => "amalgam.cache.miss",
            Self::FactorySyntheticTimeout => "amalgam.factory.synthetic_timeout",
            Self::FactoryError => "amalgam.factory.error",
            Self::FactorySuccess => "amalgam.factory.success",
            Self::FailSafeActivate => "amalgam.failsafe_activate",
            Self::EagerRefresh => "amalgam.eager_refresh",
            Self::MemorySet => "amalgam.memory.set",
            Self::MemoryGet => "amalgam.memory.get",
            Self::MemoryExpire => "amalgam.memory.expire",
            Self::MemoryRemove => "amalgam.memory.remove",
            Self::MemoryEvict => "amalgam.memory.evict",
            Self::MemoryHit => "amalgam.memory.hit",
            Self::MemoryMiss => "amalgam.memory.miss",
            Self::DistributedSet => "amalgam.distributed.set",
            Self::DistributedGet => "amalgam.distributed.get",
            Self::DistributedRemove => "amalgam.distributed.remove",
            Self::DistributedHit => "amalgam.distributed.hit",
            Self::DistributedMiss => "amalgam.distributed.miss",
            Self::DistributedCircuitBreakerChange => "amalgam.distributed.circuit_breaker_change",
            Self::SerializationError => "amalgam.serialize_error",
            Self::DeserializationError => "amalgam.deserialize_error",
            Self::BackplanePublish => "amalgam.backplane.publish",
            Self::BackplaneReceive => "amalgam.backplane.receive",
            Self::BackplaneCircuitBreakerChange => "amalgam.backplane.circuit_breaker_change",
            Self::OperationStarted => "amalgam.operation.started",
            Self::OperationCompleted => "amalgam.operation.completed",
            Self::MemoryAdmissionRejected => "amalgam.memory.admission_rejected",
            Self::BackgroundCommitError => "amalgam.background_commit.error",
            Self::MarkerRead => "amalgam.marker.read",
            Self::MarkerReceived => "amalgam.marker.receive",
            Self::MarkerSnapshotWrite => "amalgam.marker.snapshot_write",
            Self::MarkerEagerRefresh => "amalgam.marker.eager_refresh",
        }
    }
    pub(super) const fn scope(self) -> MetricScope {
        match self {
            Self::Set => MetricScope::Cache,
            Self::TryGet => MetricScope::Cache,
            Self::GetOrDefault => MetricScope::Cache,
            Self::GetOrSet => MetricScope::Cache,
            Self::Remove => MetricScope::Cache,
            Self::Expire => MetricScope::Cache,
            Self::RemoveByTag => MetricScope::Cache,
            Self::Clear => MetricScope::Cache,
            Self::Hit => MetricScope::Cache,
            Self::Miss => MetricScope::Cache,
            Self::FactorySyntheticTimeout => MetricScope::Cache,
            Self::FactoryError => MetricScope::Cache,
            Self::FactorySuccess => MetricScope::Cache,
            Self::FailSafeActivate => MetricScope::Cache,
            Self::EagerRefresh => MetricScope::Cache,
            Self::MemorySet => MetricScope::Memory,
            Self::MemoryGet => MetricScope::Memory,
            Self::MemoryExpire => MetricScope::Memory,
            Self::MemoryRemove => MetricScope::Memory,
            Self::MemoryEvict => MetricScope::Memory,
            Self::MemoryHit => MetricScope::Memory,
            Self::MemoryMiss => MetricScope::Memory,
            Self::DistributedSet => MetricScope::Distributed,
            Self::DistributedGet => MetricScope::Distributed,
            Self::DistributedRemove => MetricScope::Distributed,
            Self::DistributedHit => MetricScope::Distributed,
            Self::DistributedMiss => MetricScope::Distributed,
            Self::DistributedCircuitBreakerChange => MetricScope::Distributed,
            Self::SerializationError => MetricScope::Distributed,
            Self::DeserializationError => MetricScope::Distributed,
            Self::BackplanePublish => MetricScope::Backplane,
            Self::BackplaneReceive => MetricScope::Backplane,
            Self::BackplaneCircuitBreakerChange => MetricScope::Backplane,
            Self::OperationStarted => MetricScope::Cache,
            Self::OperationCompleted => MetricScope::Cache,
            Self::MemoryAdmissionRejected => MetricScope::Memory,
            Self::BackgroundCommitError => MetricScope::Cache,
            Self::MarkerRead => MetricScope::Cache,
            Self::MarkerReceived => MetricScope::Cache,
            Self::MarkerSnapshotWrite => MetricScope::Cache,
            Self::MarkerEagerRefresh => MetricScope::Cache,
        }
    }
}
